export const URL = 'http://192.168.1.102:3000'
// 首页
export const ARTICLE_GET_SUCCESS = 'ARTICLE_GET_SUCCESS'
export const ARTICLE_NEXT = 'ARTICLE_NEXT'
export const ARTICLE_NEXT_BUTTON_CLOSE = 'ARTICLE_NEXT_BUTTON_CLOSE'

//user
export const SIGN_TOGGLE = 'SIGN_TOGGLE'
